{
 "title": "Duet - Print Overview",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "MCU Temperature",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duet_board_mcu_temperature{board=\"0\"}",
     "legendFormat": "MCU Temperature"
    }
   ]
  },
  {
   "title": "VIN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duet_board_vin{board=\"0\"}",
     "legendFormat": "VIN"
    }
   ]
  },
  {
   "title": "Current Layer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "duet_job_current_layer", "legendFormat": "Current Layer Time" }
   ]
  },
  {
   "title": "Current Print Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "duet_job_duration_seconds", "legendFormat": "Current Print Duration" }
   ]
  },
  {
   "title": "Filament Monitor - mm per rev",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duet_filament_monitor_calibrated_mm_per_rev",
     "legendFormat": "mm/rev"
    }
   ]
  },
  {
   "title": "Filament Monitor - Percent Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duet_filament_monitor_calibrated_percent_min",
     "legendFormat": "Percent Min"
    }
   ]
  },
  {
   "title": "Filament Monitor - Percent Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duet_filament_monitor_calibrated_percent_max",
     "legendFormat": "Percent Max"
    }
   ]
  },
  {
   "title": "Filament Monitor - Total Distance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duet_filament_monitor_calibrated_total_distance",
     "legendFormat": "Total Distance (mm)"
    }
   ]
  },
  {
   "title": "Current Layer Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duet_job_current_layer_time_seconds",
     "legendFormat": "Current Layer Time"
    }
   ]
  },
  {
   "title": "Time Left - Filament",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duet_job_time_left_filament_seconds",
     "legendFormat": "Current Layer Time"
    }
   ]
  },
  {
   "title": "Time Left - File",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duet_job_time_left_file_seconds",
     "legendFormat": "Current Layer Time"
    }
   ]
  },
  {
   "title": "Time Left - Slicer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duet_job_time_left_slicer_seconds",
     "legendFormat": "Current Layer Time"
    }
   ]
  },
  {
   "title": "Filament Monitor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "duet_filament_monitor_calibrated_percent_max",
     "legendFormat": "Percent Max"
    },
    {
     "expr": "duet_filament_monitor_calibrated_percent_min",
     "legendFormat": "Percent Min"
    },
    {
     "expr": "duet_filament_monitor_calibrated_mm_per_rev",
     "legendFormat": "Sensitivity"
    },
    {
     "expr": "duet_filament_monitor_configured_mm_per_rev",
     "legendFormat": "Sensitivity (Configured)"
    },
    {
     "expr": "duet_filament_monitor_configured_percent_max",
     "legendFormat": "Percent Max (Configured)"
    },
    {
     "expr": "duet_filament_monitor_configured_percent_min",
     "legendFormat": "Percent Min (Configured)"
    }
   ]
  },
  {
   "title": "Filament Monitor Vs Layer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "duet_filament_monitor_calibrated_percent_max",
     "legendFormat": "Percent Max"
    },
    {
     "expr": "duet_filament_monitor_calibrated_percent_min",
     "legendFormat": "Percent Min"
    },
    { "expr": "duet_job_current_layer", "legendFormat": "Layer" }
   ]
  },
  {
   "title": "Filament Monitor Vs Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "duet_filament_monitor_calibrated_percent_max",
     "legendFormat": "Percent Max"
    },
    {
     "expr": "duet_filament_monitor_calibrated_percent_min",
     "legendFormat": "Percent Min"
    },
    {
     "expr": "duet_heater_current_temperature",
     "legendFormat": "Layer"
    }
   ]
  },
  {
   "title": "Heaters Vs PWM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "duet_heater_active_target_temperature",
     "legendFormat": "Active Target {{heater}}"
    },
    {
     "expr": "duet_heater_current_temperature",
     "legendFormat": "Current {{heater}}"
    },
    { "expr": "duet_heater_avg_pwm", "legendFormat": "Avg. PWM {{heater}}" }
   ]
  },
  {
   "title": "Heaters Vs Fan",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "duet_heater_active_target_temperature",
     "legendFormat": "Active Target {{heater}}"
    },
    {
     "expr": "duet_heater_current_temperature",
     "legendFormat": "Current {{heater}}"
    },
    { "expr": "duet_fans_actual_value", "legendFormat": "Fan" }
   ]
  },
  {
   "title": "Current Move",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "duet_move_current_move_acceleration_speed",
     "legendFormat": "Accelleration"
    },
    {
     "expr": "duet_move_current_move_deceleration_speed",
     "legendFormat": "Deceleration"
    },
    {
     "expr": "duet_move_current_move_requested_speed",
     "legendFormat": "Requested Speed"
    },
    {
     "expr": "duet_move_current_move_top_speed",
     "legendFormat": "Top Speed"
    }
   ]
  }
 ]
}